#!/bin/bash
# iterate through all the files in a directory

#the * is used as a wild card to run through everything following it.
for file in /home/$USER/D* /home/$USER/Documents/badfile.txt
do
    # we are putting "" around $file because on linux you can
    # have spaces in file names. 
    if [ -d "$file" ]
       then
	   echo "$file is a directory."
    elif [ -f "$file" ]
	 then
	     echo "$file is a file."
    else
	echo "$file does not exist."
    fi
done
