#!/bin/bash
# storing STDOUT, then coming back to it
exec 3>&1
exec 1>testout4

echo "This should store in the output file."
echo "And this line also."

exec 1>&3

echo "Now things are back to normal."

