#!/bin/bash
# redirecting all output to a file

exec 1>testout1

echo "This is a test of redirecting all output"
echo "from a script to another file without"
echo " having to redirect each line individually"

