#!/bin/bash
# redirecting input file descriptors
exec 6<&0
exec 0<test

count=1
while read line
do
	echo "Line #$count: $line"
	count=$[ $count +1 ]
done

exec 0<&6
read -p "Are you done now? " answer
echo
case $answer in
	Y | y) echo "goodbye" ;;
	N | n) echo "Sorry, this is the end" ;;
esac


