#!/bin/bash
# Using bc with inline input redirection 2
var1=10.1
var2=55.9
var3=23.7
var4=92

ans=$(bc <<EOF
scale = 4
a1 = ($var1 * $var2)
a2 = ($var3 * $var4)
a1 + a2
EOF
)

echo "the answer is $ans."
