#!/bin/bash
# using a temporary directory

tempdir=$(mktemp -d dir.XXXXX)
cd $tempdir
tempfile1=$(mktemp temp.XXXXX)
tempfile2=$(mktemp temp.XXXXX)

exec 7> $tempfile1
exec 8> $tempfile2

echo "Sending data to directory $tempdir"
echo "Into the distance a ribbon of black" >&7
echo "Stretched to the point of no turning back" >&8

cat $tempfile1
cat $tempfile2

rm $tempfile1; rm $tempfile2;
cd ..
rmdir "$tempdir"
